blueprint:
  name: PID-thermostat
  description: >
    Плавное управление диммером (ИК-лампой) для поддержания температуры в террариуме.

  domain: automation
  input:
    temp_sensor:
      name: Датчик температуры
      selector:
        entity:
          domain: sensor
          device_class: temperature

    ir_dimmer:
      name: Диммер (ИК-лампа)
      selector:
        entity:
          domain: light

    target_temp:
      name: Уставка температуры (°C)
      selector:
        entity:
          domain: input_number

    max_temp:
      name: Максимальная температура (°C)
      description: "При достижении этой температуры лампа выключится"
      default: 42
      selector:
        number:
          min: 30
          max: 60
          step: 0.5

    integral_var:
      name: Переменная интеграла (input_number)
      selector:
        entity:
          domain: input_number

    last_error_var:
      name: Переменная последней ошибки (input_number)
      selector:
        entity:
          domain: input_number
    kP:
      name: P-коэффициент PID
      description: P (пропорциональная) - реагирует на текущую ошибку
      default: 5
      selector:
        number:
          min: 0.1
          max: 25.0
          step: 0.1
          mode: slider
    kI:
      name: I-коэффициент PID
      description: I (интегральная) - устраняет долговременные отклонения
      default: 0
      selector:
        number:
          min: 0.01
          max: 1.0
          step: 0.01
          mode: slider
    kD:
      name: D-коэффициент PID
      description: D (дифференциальная) - предсказывает будущие изменения
      default: 0
      selector:
        number:
          min: 0.01
          max: 10.0
          step: 0.1
          mode: slider


mode: restart
trigger:
  - platform: time_pattern
    seconds: "/10"

variables:
  current_temp: "{{ states( temp_sensor ) | float(0) }}"
  target: "{{ target_temp }}"
  error: "{{ target - current_temp }}"
  prev_error: "{{ states( last_error_var ) | float(0) }}"
  integral: "{{ states( integral_var ) | float(0) + error * 10 }}"   # 10 сек интервал
  derivative: "{{ (error - prev_error) / 10 }}"
  output: >
    {% set value = (kP * error + kI * integral + kD * derivative) | round(0) %}
    {% if value < 0 %} 0
    {% elif value > 100 %} 100
    {% else %} {{ value }}
    {% endif %}

action:
  - choose:
      # Аварийное отключение при перегреве
      - conditions:
          - condition: template
            value_template: "{{ current_temp >= max_temp }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ ir_dimmer }}"
          - variables:
              integral: 0  # Сброс интеграла
          - delay: "00:05:00"  # Пауза 5 минут
    
      # Нормальный режим работы
      - conditions:
          - condition: template
            value_template: "{{ current_temp < max_temp }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ ir_dimmer }}"
            data:
              brightness_pct: "{{ pid_output }}"
              
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_temp >= max_temp }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input ir_dimmer
          - service: input_number.set_value
            data:
              entity_id: !input integral_var
              value: 0
          - service: input_number.set_value
            data:
              entity_id: !input last_error_var
              value: 0
          - service: system_log.write
            data:
              level: warning
              message: "🚨 PID Thermostat: Температура {{ current_temp }}°C >= {{ max_temp }}°C — аварийное выключение."

      - conditions:
          - condition: template
            value_template: "{{ current_temp < max_temp }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input ir_dimmer
            data:
              brightness_pct: "{{ output }}"

          - service: input_number.set_value
            data:
              entity_id: !input integral_var
              value: "{{ integral | round(2) }}"

          - service: input_number.set_value
            data:
              entity_id: !input last_error_var
              value: "{{ error | round(2) }}"

          - service: system_log.write
            data:
              level: info
              message: >
                PID Thermostat: T={{ current_temp }}°C,
                Target={{ target }}°C,
                Error={{ error | round(2) }},
                Out={{ output }}%.